#!/usr/bin/env python3
"""Generate role-tailored resume variants from the master .tex.

Per RESUME-STRATEGY.md section 29: copy the master, comment out the Adorus bullets
section 27 says to cut for that role, change NOTHING else. Same template, same macros,
same preamble - only bullet content differs.

    python3 make_variants.py
"""
import os, re, shutil

MASTER = "ShayanPoigaiResume1.tex"
OUTDIR = "variants"

# Adorus bullets, keyed as in section 27. Matched on a distinctive opener so the script
# survives line-number drift in the master.
BULLETS = {
    "A": "Built a \\textbf{two-stage image-retrieval pipeline}",
    "B": "Shipped AI virtual try-on on a reference-conditioned Gemini",
    "C": "Fixed a \\textbf{production} tax bug",
    "D": "Served private S3 imagery only through CloudFront",
    "E": "Built and operate the service behind it:",
}

# section 27 keep-sets
VARIANTS = {
    "ml":       ("ML / AI / computer vision",            ["A", "B", "C"]),
    "infra":    ("Infrastructure / platform / cloud",    ["A", "D", "E"]),
    "backend":  ("Backend / fullstack",                  ["A", "C", "E"]),
    "security": ("Security",                             ["D", "C", "A"]),
    "general":  ("General / unknown role",               ["A", "C", "D"]),
}

def build(name, label, keep):
    src = open(MASTER).read().split("\n")
    cut = [k for k in BULLETS if k not in keep]
    out, done = [], []
    for line in src:
        stripped = line.strip()
        hit = None
        if stripped.startswith("\\resumeItem{"):
            for k in cut:
                if BULLETS[k] in line:
                    hit = k
                    break
        if hit:
            indent = line[:len(line) - len(line.lstrip())]
            out.append(f"{indent}% CUT for '{name}' variant (section 27: keep {','.join(keep)}) --")
            out.append(f"{indent}% {stripped}")
            done.append(hit)
        else:
            out.append(line)

    # header note, inserted right after \begin{document} so it never touches the preamble
    for i, l in enumerate(out):
        if l.strip().startswith("\\begin{document}"):
            out.insert(i, f"% === VARIANT: {name} — {label} ===")
            out.insert(i + 1, f"% Adorus bullets kept: {', '.join(keep)}  |  cut: {', '.join(cut) or 'none'}")
            out.insert(i + 2, "% Generated by make_variants.py. Do not hand-edit - regenerate.")
            out.insert(i + 3, "% Template is IDENTICAL to the master; only bullet content differs.")
            break

    path = os.path.join(OUTDIR, f"ShayanPoigaiResume-{name}.tex")
    open(path, "w").write("\n".join(out))
    missing = [k for k in cut if k not in done]
    return path, len(done), missing

def main():
    os.makedirs(OUTDIR, exist_ok=True)
    master_pre = open(MASTER).read().split("\\begin{document}")[0]
    print(f"master: {MASTER}\n")
    for name, (label, keep) in VARIANTS.items():
        path, n, missing = build(name, label, keep)
        flag = "" if not missing else f"  !! NOT FOUND: {missing}"
        print(f"  {name:9s} keep {','.join(keep):9s} cut {n}  ->  {path}{flag}")
        # verify the preamble is byte-identical to the master
        got_pre = open(path).read().split("\\begin{document}")[0]
        # strip the variant header comments we inserted before \begin{document}
        got_pre = "\n".join(l for l in got_pre.split("\n") if not l.startswith("% ==="
                            ) and not l.startswith("% Adorus bullets kept:"
                            ) and not l.startswith("% Generated by make_variants"
                            ) and not l.startswith("% Template is IDENTICAL"))
        assert got_pre.rstrip() == master_pre.rstrip(), f"PREAMBLE DRIFT in {name}"
    print("\nAll preambles verified byte-identical to the master.")
    print("Compile in Overleaf, then re-run the section 28 parse check on each PDF.")

if __name__ == "__main__":
    main()
